In [1]:
import numpy as np

## 二元运算

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
a + 1

array([2, 3, 4, 5])

In [4]:
b = np.array([2, 3, 4 ,5])
b

array([2, 3, 4, 5])

In [5]:
a * b

array([ 2,  6, 12, 20])

In [6]:
a + b

array([3, 5, 7, 9])

In [7]:
a > 2

array([False, False,  True,  True])

## 产生`numpy`数组

In [8]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

1. 产生全0、全1数组

In [9]:
z = np.zeros(5)
t = np.ones(6)
print(z)
print(t)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


2. `dtype`指定数据类型

In [10]:
np.zeros(5, dtype='bool')

array([False, False, False, False, False])

3. `fill` 设置指定值

In [11]:
print(a)
a.fill(10)
a

[2 3 4]


array([10, 10, 10])

> `array`中要求所有 `dtype` 均相同

4. 强制数据类型转换

In [12]:
a = a.astype('int')
print(type(a[0]))
a = a.astype('float')
print(type(a[0]))

<class 'numpy.int32'>
<class 'numpy.float64'>


5. 产生特殊数组

In [13]:
np.arange(1, 10, 2)  # 从1到10 步长为2

array([1, 3, 5, 7, 9])

In [14]:
np.linspace(1, 10, 5) # 从1 到 10 均匀取5个点

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

>作为序列生成器， numpy.linspace()函数用于在线性空间中以均匀步长生成数字序列。
Numpy通常可以使用numpy.arange()生成序列，但是当我们使用浮点参数时，可能会导致精度损失，这可能会导致不可预测的输出。为了避免由于浮点精度而造成的任何精度损失，numpy在numpy.linspace()为我们提供了一个单独的序列生成器，如果您已经知道所需的元素数，则这是首选。 但是通常使用带有适当参数的linspace()和 arange()可以得到相同的输出，因此可以为同一任务选择两者。

In [15]:
np.random.rand(10) # 随机数

array([0.01236389, 0.24589767, 0.71497189, 0.07866579, 0.18867513,
       0.39601592, 0.73511928, 0.73429912, 0.92289115, 0.96397675])

In [16]:
np.random.randn(10)

array([-1.54443406e-01,  4.36963681e-01,  2.44844879e-01,  1.34187530e+00,
       -8.84903249e-04, -1.59865356e+00, -4.96738900e-01,  2.00288232e+00,
        2.95084437e-01,  1.32608901e+00])

In [17]:
np.random.randint(1, 10, 10)

array([6, 7, 6, 1, 4, 8, 9, 9, 1, 8])

## 数组属性

1. 数组类型

In [18]:
type(a)

numpy.ndarray

2. 数组元素类型

In [19]:
a.dtype

dtype('float64')

3. 数组大小

In [20]:
a.size  # return tuple

3

In [21]:
a.shape

(3,)

4. 数组维度

In [22]:
a.ndim

1

## 索引 切片

In [23]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

1. 取数

In [24]:
a[0]

1

2. 切片

In [25]:
a[1:-2] # 左闭右开

array([2, 3])

In [26]:
a[-4:3]

array([2, 3])

In [27]:
a[-2:]

array([4, 5])

## 多维数组

In [28]:
a = np.array(
    [[0, 1, 2, 3],
    [10, 11, 12, 13]]
)
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

经典属性

In [29]:
a.shape

(2, 4)

In [30]:
a.size

8

In [31]:
a.ndim

2

## 多维数组索引

In [32]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

1. 取数

In [33]:
a[1, 3]

13

2. 索引一整行

In [34]:
a[1]

array([10, 11, 12, 13])

## 多维数组切片

In [35]:
a = np.array([
    [1, 6, 3, 8, 5],
    [7, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [9, 2, 9, 4, 5],
    [1, 2, 3, 4, 5],
    
])
a

array([[1, 6, 3, 8, 5],
       [7, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [9, 2, 9, 4, 5],
       [1, 2, 3, 4, 5]])

1. $a[row_{start}:row_{end}, col_{start}:col_{end}]$ 

In [36]:
a[1:4, 0:3]

array([[7, 2, 3],
       [1, 2, 3],
       [9, 2, 9]])

2. $[lower:upper:step]$

In [37]:
a[:, ::2] # 取出0， 2， 4

array([[1, 3, 5],
       [7, 3, 5],
       [1, 3, 5],
       [9, 9, 5],
       [1, 3, 5]])

In [38]:
"""
取出
[0, 1], [0, 3]
[2, 1], [2, 3]
"""
a[0:3:2, 1:4:2]

array([[6, 8],
       [2, 4]])

## 切片是引用

指针指向内存中 $a$ 的区域，所以修改切片也修改了原数组,
解决：`copy()`

In [39]:
a = np.array([0, 1, 5, 6])
a

array([0, 1, 5, 6])

In [40]:
b = a[0:3]
b[1] = 10000
a

array([    0, 10000,     5,     6])

In [41]:
c = a[0:3].copy()
c[2] = 9999
a

array([    0, 10000,     5,     6])

## 花式索引

1. 一维索引(索引数组取数)

In [42]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

指定索引数组

In [43]:
index = [1, 2, 6]
y = a[index]
y

array([10, 20, 60])

指定布尔数组(长度和数组长度相等)

In [44]:
mask = np.array([0, 2, 3, 0, 0, 2, 2, 2, 0, 0], dtype=bool)
a[mask]

array([10, 20, 50, 60, 70])

2. 二维索引

In [45]:
a = np.array([
    [1, 6, 3, 8, 77],
    [7, 2, 3, 88, 5],
    [1, 2, 99, 4, 5],
    [9, 55, 9, 4, 5],
    [33, 2, 3, 4, 5],
    
])
a

array([[ 1,  6,  3,  8, 77],
       [ 7,  2,  3, 88,  5],
       [ 1,  2, 99,  4,  5],
       [ 9, 55,  9,  4,  5],
       [33,  2,  3,  4,  5]])

取出次对角线

In [46]:
a[(0, 1, 2, 3, 4), (4, 3, 2, 1, 0)]

array([77, 88, 99, 55, 33])

取出最后三行的1，3，5列

In [47]:
a[3:, [0, 2, 4]]

array([[ 9,  9,  5],
       [33,  3,  5]])

In [48]:
mask = np.array([1, 0, 1, 0, 1], dtype="bool")
a[mask, 2]

array([ 3, 99,  3])

**花式索引返回复制,不是引用**

##  不完全索引

In [49]:
y = a[:3]
y

array([[ 1,  6,  3,  8, 77],
       [ 7,  2,  3, 88,  5],
       [ 1,  2, 99,  4,  5]])

## `where` 索引

返回所有非零元素索引(返回元组)

In [50]:
a = np.array([0, 5, 4, 1, 0, 0, 5])
np.where(a)

(array([1, 2, 3, 6], dtype=int64),)

返回特定条件(返回元组)

In [51]:
np.where(a > 1) # a > 1  => bool array 

(array([1, 2, 6], dtype=int64),)

In [52]:
a[np.where(a > 1)]

array([5, 4, 5])

数组操作返回`array`

In [53]:
a[a > 1]

array([5, 4, 5])

## 数据类型

## 类型转换

1. `dtype`

In [54]:
a = np.array([1, 2, 5], dtype=float)
a

array([1., 2., 5.])

2. `asarray`

In [55]:
a = np.asarray(a, dtype=int)
a

array([1, 2, 5])

3. `astype`

In [56]:
b = a.astype(float)
b

array([1., 2., 5.])

## 数组排序

In [57]:
a = np.array([2, 5, 4, 8, 9, 7], dtype=int)
a

array([2, 5, 4, 8, 9, 7])

In [58]:
np.sort(a)

array([2, 4, 5, 7, 8, 9])

In [59]:
a

array([2, 5, 4, 8, 9, 7])

> 注意是返回新数组

`argsort`函数

`argsort`返回从小到大的排列在数组中的索引位置

In [60]:
order = np.argsort(a)
order

array([0, 2, 1, 5, 3, 4], dtype=int64)

## 数组整体操作

1. 和

In [61]:
np.sum(a)

35

2. 极值

In [62]:
np.max(a)

9

In [63]:
a.max()

9

In [64]:
np.min(a)

2

In [65]:
a.min()

2

3. 均值

In [66]:
a.mean()

5.833333333333333

In [67]:
np.mean(a)

5.833333333333333

4. 标准差

In [68]:
np.std(a)

2.4094720491334933

In [69]:
np.std(a)

2.4094720491334933

5. 相关系数矩阵 $cov(X, Y)$

In [70]:
a = np.array([2, 5, 4, 8, 9, 7], dtype=int)
a

array([2, 5, 4, 8, 9, 7])

In [71]:
b = np.array([1, 2, 3, 4, 5, 4], dtype=int)
b

array([1, 2, 3, 4, 5, 4])

In [72]:
np.cov(a, b)

array([[6.96666667, 3.63333333],
       [3.63333333, 2.16666667]])

## 多维数组操作

1. 数组形状

In [75]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [78]:
a.shape = 2, 3
a

array([[0, 1, 2],
       [3, 4, 5]])

> 修改原数组

In [81]:
b = a.reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

2. 转置

In [83]:
print(a)
print('*'*20)
print(a.T)

[[0 1 2]
 [3 4 5]]
********************
[[0 3]
 [1 4]
 [2 5]]


In [85]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [86]:
a

array([[0, 1, 2],
       [3, 4, 5]])

> 原数组不变

## 数组连接

In [87]:
x = np.array([[0, 1, 2], [2, 3, 4]])
y = np.array([[2, 5, 6], [5, 6, 7]])

**将两个数组包裹在一个元组当中**

In [90]:
z = np.concatenate((x, y))  # 默认沿着第一维进行连接
z

array([[0, 1, 2],
       [2, 3, 4],
       [2, 5, 6],
       [5, 6, 7]])

In [91]:
z = np.concatenate((x, y), axis=1)  # 指定沿着第二维连接
z

array([[0, 1, 2, 2, 5, 6],
       [2, 3, 4, 5, 6, 7]])

增加维度拼接

In [93]:
z = np.array((x, y))  # 将两个形状相同二维数组拼接成三维数组 （摞一起）
z

array([[[0, 1, 2],
        [2, 3, 4]],

       [[2, 5, 6],
        [5, 6, 7]]])

In [94]:
np.vstack((x,y))

array([[0, 1, 2],
       [2, 3, 4],
       [2, 5, 6],
       [5, 6, 7]])

In [95]:
np.hstack((x, y))

array([[0, 1, 2, 2, 5, 6],
       [2, 3, 4, 5, 6, 7]])

In [96]:
np.dstack((x, y))

array([[[0, 2],
        [1, 5],
        [2, 6]],

       [[2, 5],
        [3, 6],
        [4, 7]]])

## 一些内置函数

In [99]:
a = np.array([-1, -5, 5, 10])
a

array([-1, -5,  5, 10])

In [101]:
np.abs(a)

array([ 1,  5,  5, 10])

In [102]:
np.exp(a)

array([3.67879441e-01, 6.73794700e-03, 1.48413159e+02, 2.20264658e+04])

In [103]:
np.median(a)

2.0

In [106]:
np.cumsum(a)  # 加到当前位的加和结果

array([-1, -6, -1,  9], dtype=int32)

查文档